name: Build

on: [push]

env:
  CIBW_SKIP: cp34-* cp35-* *-manylinux_i686 *-win32
  CIBW_BUILD: cp3?-*

jobs:
  build_wheels:
    name: Build wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-python@v1
      name: Install Python
      with:
        python-version: '3.7'

    - name: Install cibuildwheel
      run: |
        python -m pip install cibuildwheel==1.3.0
    - name: Build wheel
      run: |
        python -m cibuildwheel --output-dir dist
    - name: Look
      run: |
        ls dist
    - uses: actions/upload-artifact@v1
      with:
        name: wheels
        path: ./dist

  build_source:
    runs-on: ubuntu-latest
    needs: [build_wheels]

    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-python@v1
      name: Install Python
      with:
        python-version: '3.7'
    
    - name: Build source
      run: |
        python setup.py sdist -d ./dist
    - name: Look
      run: |
        ls dist

  upload:
    runs-on: ubuntu-latest
    needs: [build_source]
    
    steps:
    - name: Publish distribution 📦 to Test PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.testpypi_password }}
        repository_url: https://test.pypi.org/legacy/
    - name: Publish distribution 📦 to PyPI
      if: startsWith(github.event.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.pypi_password }}